#!/bin/bash
# ============================================================
# 02_server_apache.sh
# Generates Server Certificate and Configures Apache HTTPS
# Requires:
#   config.sh
#   Root/Sub CA files generated by 01_root_subca.sh
# ============================================================

set -e

if [ ! -f config.sh ]; then
    echo "[ERROR] config.sh not found."
    exit 1
fi

source config.sh

cd "$OUTPUT_DIR"

echo "=============================================="
echo " SERVER CERTIFICATE & APACHE CONFIGURATION"
echo "=============================================="

############################################################
# Create server.ext
############################################################

echo "[1/15] Creating server.ext..."

IFS=',' read -ra SAN_ARRAY <<< "$SAN"

cat > server.ext <<EOF
basicConstraints=CA:FALSE
keyUsage=digitalSignature,keyEncipherment
extendedKeyUsage=serverAuth
subjectAltName=@alt_names

[alt_names]
EOF

COUNT=1
for NAME in "${SAN_ARRAY[@]}"
do
    echo "DNS.$COUNT=$(echo "$NAME" | xargs)" >> server.ext
    COUNT=$((COUNT+1))
done

############################################################
# Generate Server Key
############################################################

echo "[2/15] Generating Server Key..."

openssl genpkey \
    -algorithm RSA \
    -pkeyopt rsa_keygen_bits:$KEY_SIZE \
    -out server.key

############################################################
# Generate Server CSR
############################################################

echo "[3/15] Generating Server CSR..."

openssl req \
    -new \
    -key server.key \
    -out server.csr \
    -subj "/C=$COUNTRY/ST=$STATE/L=$CITY/O=$ORG/OU=$OU/CN=$DOMAIN"

############################################################
# Sign Server Certificate
############################################################

echo "[4/15] Signing Server Certificate..."

openssl x509 \
    -req \
    -in server.csr \
    -CA sub.crt \
    -CAkey sub.key \
    -CAcreateserial \
    -out server.crt \
    -days "$SERVER_VALIDITY" \
    -extfile server.ext

############################################################
# Verify Certificate
############################################################

echo "[5/15] Verifying Server Certificate..."

openssl x509 -in server.crt -text -noout

############################################################
# Build Full Chain
############################################################

echo "[6/15] Building Certificate Chain..."

cat server.crt sub.crt > fullchain.crt

############################################################
# Install Apache
############################################################

echo "[7/15] Installing Apache..."

apt-get update
apt-get install -y apache2

############################################################
# Enable SSL
############################################################

echo "[8/15] Enabling SSL..."

a2enmod ssl

############################################################
# Website Directory
############################################################

echo "[9/15] Creating Website..."

mkdir -p "$WEBROOT"

cat > "$WEBROOT/index.html" <<EOF
<!DOCTYPE html>
<html>
<head>
<title>$DOMAIN</title>
</head>
<body style="font-family:Arial;text-align:center;margin-top:80px;">
<h1>HTTPS Successfully Configured</h1>
<h2>$DOMAIN</h2>
<p>Certificate issued by Sub CA</p>
</body>
</html>
EOF

chown -R www-data:www-data "$WEBROOT"

############################################################
# Apache VirtualHost
############################################################

echo "[10/15] Creating VirtualHost..."

cat > /etc/apache2/sites-available/$SITE_NAME.conf <<EOF
<VirtualHost *:443>

ServerName $DOMAIN

DocumentRoot $WEBROOT

SSLEngine on

SSLCertificateFile $OUTPUT_DIR/fullchain.crt
SSLCertificateKeyFile $OUTPUT_DIR/server.key

<Directory $WEBROOT>
Options Indexes FollowSymLinks
AllowOverride All
Require all granted
</Directory>

ErrorLog \${APACHE_LOG_DIR}/${SITE_NAME}_error.log
CustomLog \${APACHE_LOG_DIR}/${SITE_NAME}_access.log combined

</VirtualHost>
EOF

############################################################
# Configure Apache ServerName
############################################################

echo "[11/15] Configuring Apache..."

grep -q "^ServerName $DOMAIN" /etc/apache2/apache2.conf || \
echo "ServerName $DOMAIN" >> /etc/apache2/apache2.conf

############################################################
# Enable Site
############################################################

echo "[12/15] Enabling Site..."

a2ensite "$SITE_NAME.conf"

if [ -f /etc/apache2/sites-enabled/000-default.conf ]; then
    a2dissite 000-default.conf
fi

############################################################
# Configure Hosts (Local Testing)
############################################################

echo "[13/15] Updating /etc/hosts..."

grep -q "$DOMAIN" /etc/hosts || \
echo "$SERVER_IP $DOMAIN" >> /etc/hosts

############################################################
# Restart Apache
############################################################

echo "[14/15] Restarting Apache..."

systemctl reload apache2
systemctl restart apache2

############################################################
# Summary
############################################################

echo "[15/15] Completed."

echo
echo "=============================================="
echo "SERVER CONFIGURATION COMPLETED"
echo "=============================================="

echo
echo "Generated Files:"
echo "-----------------------------"
echo "server.key"
echo "server.csr"
echo "server.crt"
echo "server.ext"
echo "fullchain.crt"

echo
echo "Apache Site : $SITE_NAME"
echo "Website     : https://$DOMAIN"
echo "Web Root    : $WEBROOT"

exit 0